chat/urls.py
from django.conf.urls import patterns, include, url

from chat.views import show_contact_list, check_username, send_message, show_chat, send_message_api

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'quests.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^contact_list/$', show_contact_list, name='contact_list'),
    url(r'^check_username/$', check_username, name='check_username'),
    url(r'^chat/(?P<id>\d+)/$', show_chat, name='chat'),
    url(r'^send_message/$', send_message, name='send_message'),
    url(r'^send_message_api/$', send_message_api, name='send_message_api'),
    )

quests/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.contrib.auth.views import password_change_done, password_change

from web.views import registration, index, restore_password, logout_view, login_view, EventView, confirm_join_event, \
    create_team, join_team, join_event, PlayerView, OrganizerView, show_my_profile, create_event, add_task, delete_task, \
    edit_task, delete_event, delete_team, leave_team, unregister_event, upload_photos, delete_photo, play_event, \
    start_task, task_answer, complete_event, show_my_organizer_profile, EventsListView, AllEventsListView, \
    search_events_view, PlayersListView, search_players_view, OrganizerListView, search_organizers_view, \
    events_registered_view, player_event_management, photo_gallery, team_management, get_hint, current_events_view, \
    complete_event_organizer, show_completed_event_organizer

from pages.urls import urlpatterns as pages_url

from filebrowser.sites import site

from quests.settings import MEDIA_ROOT

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'quests.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', index, name='index'),
    url(r'^event/(?P<pk>\d+)/$', EventView.as_view(), name='event'),
    url(r'^player/(?P<pk>\d+)/$', PlayerView.as_view(), name='player'),
    url(r'^organizer/(?P<pk>\d+)/$', OrganizerView.as_view(), name='organizer'),
    url(r'^my_profile/$', show_my_profile, name='player_profile'),
    url(r'^my_organizer_profile/$', show_my_organizer_profile, name='organizer_profile'),
    url(r'^my_profile/event_management/$', player_event_management, name='player_event_management'),
    url(r'^my_profile/photo_gallery/$', photo_gallery, name='photo_gallery'),
    url(r'^my_profile/teams/$', team_management, name='team_management'),
    url(r'^my_profile/change_password/$', password_change, {'template_name': 'password_change.html'},  name='password_change'),
    url(r'^my_profile/change_password_done/', password_change_done, {'template_name': 'password-done.html'}, name='password_change_done'),
    url(r'^confirm_join/(?P<pk>\d+)/$', confirm_join_event, name='confirm_join'),
    url(r'^join/(?P<flag>\w+)/$', join_event, name='join_event'),
    url(r'^unregister_event/$', unregister_event, name='unregister_event'),
    url(r'^create_team/$', create_team, name='create_team'),
    url(r'^create_event/$', create_event, name='create_event'),
    url(r'^create_event/(?P<pk>\d+)/$', create_event, name='edit_event'),
    url(r'^add_task/$', add_task, name='add_task'),
    url(r'^delete_task/$', delete_task, name='delete_task'),
    url(r'^edit_task/$', edit_task, name='edit_task'),
    url(r'^delete_event/$', delete_event, name='delete_event'),
    url(r'^join_team', join_team, name='join_team'),
    url(r'^create_team/(?P<event_pk>\d+)/$', create_team, name='create_and_register_team'),
    url(r'^delete_team/$', delete_team, name='delete_team'),
    url(r'^leave_team/$', leave_team, name='leave_team'),
    url(r'^upload_photo/$', upload_photos, name='upload_photos'),
    url(r'^delete_photo/$', delete_photo, name='delete_photo'),
    url(r'^play_event/(?P<pk>\d+)/$', play_event, name='play_event'),
    url(r'^start_task/$', start_task, name='start_task'),
    url(r'^task_answer/$', task_answer, name='task_answer'),
    url(r'^complete_event/$', complete_event, name='complete_event'),
    url(r'^current_event/(?P<pk>\d+)/$', current_events_view, name='current_event'),
    url(r'^complete_event_organizer/$', complete_event_organizer, name='complete_event_organizer'),
    url(r'^show_completed_event/(?P<pk>\d+)/$', show_completed_event_organizer, name='show_completed_event_organizer'),
    url(r'^get_hint/$', get_hint, name='get_hint'),
    url(r'^register/$', registration, name='register'),
    url(r'^restore/$', restore_password, name='restore'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^events/$', EventsListView.as_view(), name='events'),
    url(r'^events/all/$', AllEventsListView.as_view(), name='all_events'),
    url(r'^events/search/$', search_events_view, name='search_events'),
    url(r'^events/registered/', events_registered_view, name='events_registered'),
    url(r'^players/$', PlayersListView.as_view(), name='players'),
    url(r'^players/search/$', search_players_view, name='search_players'),
    url(r'^organizers/$', OrganizerListView.as_view(), name='organizers'),
    url(r'^organizers/search/$', search_organizers_view, name='search_organizers'),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    url(r'^messages/', include('chat.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^pages/', include(pages_url)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

web/forms.py
__author__ = 'kodiers'

from django import forms
from django.utils.translation import ugettext_lazy as _

from web.models import Events, COUNTRIES


class UserRegistrationForm(forms.Form):
    """
    Form for registration new user
    """
    login = forms.CharField(label=_("Nickname"), max_length=128)
    email = forms.EmailField(label=_("Email"), max_length=128)
    password1 = forms.CharField(label=_("Password"), max_length=128, widget=forms.PasswordInput,
                                min_length=8)
    password2 = forms.CharField(label=_("Confirm password"), max_length=128,
                                widget=forms.PasswordInput, min_length=8)
    is_organizer = forms.BooleanField(label=_("Are you organizer?"), required=False)


class RestorePasswordForm(forms.Form):
    """
    Restore password form
    """
    email = forms.EmailField(label="Email", max_length=128)


class CreateTeamForm(forms.Form):
    """
    Create team form
    """
    title = forms.CharField(label=_("Title"), max_length=128)


class PlayerProfileForm(forms.Form):
    """
    Change player profile form
    """
    SEX = (
        ('0', _('MALE')),
        ('1', _('FEMALE')),
        ('2', _('NOT DEFINED'))
    )
    avatar = forms.ImageField(label=_("Avatar"), required=False)
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), label=_("About me"), required=False)
    date_of_birth = forms.DateField(label=_("Date of birth"), required=False)
    sex = forms.ChoiceField(choices=SEX, label=_('Sex'), required=False)
    country = forms.ChoiceField(required=False, label=_("Country"), choices=COUNTRIES, initial='RU')
    city = forms.CharField(max_length=255, required=False, label=_("City"))
    street = forms.CharField(required=False, label=_("Street"), widget=forms.Textarea(attrs={'rows': 1}))
    phone = forms.CharField(required=False, label=_('Phone number'), max_length=15)
    skype = forms.CharField(max_length=255, label="Skype", required=False)
    site = forms.CharField(label="Web site", required=False)
    email = forms.EmailField(label="Email")
    show_personal_info = forms.BooleanField(label=_("Show my personal info"), required=False)


class CreateEventForm(forms.ModelForm):
    """
    Model Form for create event.
    Add fields to create and edit EventPlaces object and generate map.
    """
    country = forms.ChoiceField(label=_("Country"), choices=COUNTRIES, initial='RU')
    city = forms.CharField(max_length=255, required=False, label=_("City"))
    street = forms.CharField(required=False, label=_("Street"), max_length=255)
    class Meta:
        model = Events
        fields = ['title', 'description', 'is_team', 'start_date', 'end_date', 'duration', 'image',
                  'max_players', 'min_players', 'organizer']
        widgets = {'organizer':forms.HiddenInput(), 'title': forms.Textarea(attrs={'rows': 1}),
                   'description': forms.Textarea(attrs={'rows': 5})}


class OrganizerProfileForm(forms.Form):
    """
    Change organizer profile form
    """
    avatar = forms.ImageField(label=_("Avatar"), required=False)
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), label=_("About me"), required=False)
    date_of_birth = forms.DateField(label=_("Date of birth"), required=False)
    country = forms.ChoiceField(required=False, label=_("Country"), choices=COUNTRIES, initial='RU')
    city = forms.CharField(max_length=255, required=False, label=_("City"))
    street = forms.CharField(required=False, label=_("Street"), widget=forms.Textarea(attrs={'rows': 1}))
    phone = forms.CharField(required=False, label=_('Phone number'), max_length=15)
    skype = forms.CharField(max_length=255, label="Skype", required=False)
    site = forms.CharField(label="Web site", required=False)
    email = forms.EmailField(label="Email")

templates/organizer_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load tags %}
{% load i18n %}
{% block title %}
    {{ object.username }} | {% show_title_page %}
{% endblock %}
{% block scripts %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/organizer_profile.css'%}">
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/delete_photo.js' %}"></script>
    <script src="{% static 'js/uploads_modal.js' %}"></script>
    <script src="{% static 'js/delete_event.js' %}"></script>
{% endblock %}
{% block content %}
    {% include 'profile_header.html' %}
    <div class="container-fluid">
        <div class="row row-padding block-bottom-line">
            <div class="col-md-12 text-center">
                <a href="{% url 'contact_list' %}" class="btn mybtn mybtn-small">{% trans 'Messages' %}</a>
                <a href="{% url 'password_change' %}" class="btn mybtn mybtn-small">{% trans 'Change password' %}</a>
                <a href="{% url 'create_event' %}" class="btn mybtn mybtn-small">{% trans 'Create event' %}</a>
                <a href="{% url 'create_team' %}" class="btn mybtn mybtn-small">{% blocktrans %}Create team{% endblocktrans %}</a>
                <a href="{% url 'player_event_management' %}" class="btn mybtn mybtn-small">{% trans "Event management" %}</a>
                <a href="{% url 'photo_gallery' %}" class="btn mybtn mybtn-small">{% trans "Photo gallery" %}</a>
                <a href="{% url 'team_management' %}" class="btn mybtn mybtn-small">{% trans "My teams" %}</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row block-bottom-line">
            <div class="col-md-12">
                <h1 class="color-header">{% trans 'Today events (not started)' %}</h1>
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <td>{% trans 'Title' %}</td>
                            <td class="cell-no-display">{% trans 'Start date' %}</td>
                            <td>{% trans 'Registered' %}</td>
                            <td>{% trans 'Team game' %}</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for event in object.organizers.get_today_events %}
                        <tr>
                            <td>
                                <a href="{% url 'current_event' event.pk %}">
                                    <h4>{{ event.title }}</h4>
                                </a>
                            </td>
                            <td class="cell-no-display">{{ event.start_date|date:'d-m-Y H:i' }}</td>
                            <td>{{ event.get_registered_count }}</td>
                            <td>
                                {% if event.is_team %}
                                    {% trans 'Yes' %}
                                {% else %}
                                    {% trans 'No' %}
                                {% endif %}
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="4">
                                <h5 class="color-header">{% trans 'No events today' %}</h5>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h2 class="color-header">{% blocktrans %}Change personal info:{% endblocktrans %}</h2>
                <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {% trans 'Current avatar' %}:
                        {% if object.questsusers.image.url != None %}
                            <img src="{{ object.questsusers.image.url }}" class="img-responsive img-rounded content-icon block-icon avatar-image" alt="{{ object.username }}">
                        {% else %}
                            <img src="{% static 'images/no-players-image.png' %}" class="img-responsive img-rounded content-icon block-icon avatar-image" alt="{{ object.username }}">
                        {% endif %}
                        <br>
                        <label for="id_avatar">{% blocktrans %}Change avatar:{% endblocktrans %}</label>
                        <input id="id_avatar" name="avatar" type="file">
                    </div>
                    <div class="form-group">
                        <label for="id_email">{{ form.email.label }}:</label>
                        {{ form.email|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_description">{{ form.description.label }}:</label>
                        {{ form.description|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_country">{{ form.country.label }}:</label>
                        {{ form.country|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_city">{{ form.city.label }}:</label>
                        {{ form.city|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_street">{{ form.street.label }}:</label>
                        {{ form.street|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_phone">{{ form.phone.label }}:</label>
                        {{ form.phone|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_skype">{{ form.skype.label }}:</label>
                        {{ form.skype|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_site">{{ form.site.label }}:</label>
                        {{ form.site|add_class_to_formfield:"form-control" }}
                    </div>
                    <input type="submit" value="Save!" class="mybtn mybtn-small">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/organizers.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tags %}
{% load i18n %}
{% block title %}
    {% trans 'Organizers' %} | {% show_title_page %}
{% endblock %}
{% block scripts %}
    <link href="{% static 'css/organizers.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row all-button-row">
            <div class="col-md-6">
                <form method="get" action="{% url 'search_organizers' %}" class="form-inline">
                    <label for="id_search">{% trans 'Enter word to search' %}:</label>
                    <input type="text" name="search" class="form-control" id="id_search">
                    <button type="submit" class="mybtn mybtn-small">
                        {% trans 'Search' %}
                    </button>
                    <a class="tooltips additional-link" data-toggle="collapse" href="#additionalSearchFields" aria-expanded="false" aria-controls="additionalSearchFields">
                        {% trans 'Additional parameters' %}
                    </a><span class="glyphicon glyphicon-chevron-down tooltips"></span>
                    <div class="collapse" id="additionalSearchFields">
                        <div class="well additional-div">
                            <div class="row additional-search-parameters">
                                <div class="col-xs-6">
                                    <label for="id_country">{% trans 'Country' %}</label>
                                    <select class="form-control countries-select" name="country" id="id_country">
                                        {% for country in COUNTRIES %}
                                            {% if country.0 == 'RU' %}
                                                <option value="{{ country.0 }}" selected="selected">
                                                    {{ country.1 }}
                                                </option>
                                            {% else %}
                                                <option value="{{ country.0 }}">{{ country.1 }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-xs-6">
                                    <label for="id_city">{% trans 'City' %}</label>
                                    <input type="text" class="form-control" name="city" id="id_city">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row content-row caption-row organizers-background">
            <div class="col-md-4 icon-block">
                <img src="{% static 'images/best-organizers_2.png' %}" class="content-icon" alt="{% trans 'Organizers' %}">
            </div>
            <div class="col-md-8 caption-block">
                <h1 class="page-h1">{% trans 'Organizers' %}</h1>
            </div>
        </div>
        <div class="row">
            {% for object in object_list %}
                <div class="col-md-6 show-hided-block">
                    <div class="row caption-row content-row">
                        <div class="col-md-4 icon-block">
                            {% if object.user.questsusers.image.url != None %}
                                <img src="{{ object.user.questsusers.image.url }}" class="img-responsive img-rounded content-icon block-icon events-icon" alt="{{ object.user.username }}">
                            {% else %}
                                <img src="{% static 'images/no-organizers-image.png' %}" class="img-responsive img-rounded content-icon block-icon events-icon" alt="{{ object.user.username }}">
                            {% endif %}
                        </div>
                        <div class="col-md-8">
                            <a href="{% url 'organizer' object.pk %}"> <h2>{{ object.user.username }}</h2></a>
                        </div>
                    </div>
                    {% if object.description != None%}
                        <div class="row description-row">
                            <div class="col-md-12">
                                <p>{{ object.description|truncatewords:30 }}</p>
                            </div>
                        </div>
                    {% endif %}
                    <div class="hided-hovered-block">
                        <div class="col-md-4">
                            <p>Email: {{ object.user.email }}</p>
                            <p>{% trans 'Country' %}: {{ object.user.contacts.get_country_display }}</p>
                            <p>{% trans 'City' %}: {{ object.user.contacts.city }}</p>
                            <p>{% trans 'Site' %}: {{ object.user.contacts.site }}</p>
                            <a href="{% url 'organizer' object.pk %}" class="mybtn mybtn-small">
                                {% trans 'More...' %}
                            </a>
                        </div>
                        <div class="col-md-8 organizers-events-list">
                            <h3>{% blocktrans %}Future events{% endblocktrans %}:</h3>
                            {% for event in object.get_three_future_events %}
                                <h4><a href="{% url 'event' event.pk %}"> {{ event.title }} </a></h4>
                                <p>{% trans 'Start date' %}: {{ event.start_date }}</p>
                            {% empty %}
                                {% blocktrans %}No future events{% endblocktrans %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="col-xs-12">
                    {% blocktrans %}Sorry, no organizers found.{% endblocktrans %}
                </div>
            {% endfor %}
        </div>
        <div class="row helper-block">
            <div class="col-xs-12">
                {% if is_paginated %}
                    <div class="pagination">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">
                                <span class="glyphicon glyphicon-menu-left"></span>{% trans 'Previous' %}
                            </a>
                        {% endif %}
                            {{ page_obj.number }} {% trans "Of" %} {{ page_obj.paginator.num_pages }}.
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">
                                {% trans 'Next' %}<span class="glyphicon glyphicon-menu-right"></span>
                            </a>
                        {% endif %}
                    </div>
                {% elif object_list.paginator.num_pages > 1 %}
                    <div class="pagination">
                        {% if object_list.has_previous %}
                            <a href="?page={{ object_list.previous_page_number }}{% for key, value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">
                                <span class="glyphicon glyphicon-menu-left"></span>{% trans 'Previous' %}
                            </a>
                        {% endif %}
                        {{ object_list.number }} ({{ object_list.paginator.num_pages }})
                        {% if object_list.has_next %}
                            <a href="?page={{ object_list.next_page_number }}{% for key, value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">
                                {% trans 'Next' %}<span class="glyphicon glyphicon-menu-right"></span>
                            </a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/player_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load tags %}
{% load i18n %}
{% block title %}
    {{ object.username }} | {% show_title_page %}
{% endblock %}
{% block scripts %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/calendar.js' %}"></script>
{% endblock %}
{% block content %}
    {% include 'profile_header.html' %}
    <div class="container-fluid">
        <div class="row row-padding block-bottom-line">
            <div class="col-md-12 text-center">
                <a href="{% url 'contact_list' %}" class="btn mybtn mybtn-small">{% trans 'Messages' %}</a>
                <a href="{% url 'password_change' %}" class="btn mybtn mybtn-small">{% trans 'Change password' %}</a>
                <a href="{% url 'create_event' %}" class="btn mybtn mybtn-small">{% trans 'Create event' %}</a>
                <a href="{% url 'create_team' %}" class="btn mybtn mybtn-small">{% blocktrans %}Create team{% endblocktrans %}</a>
                <a href="{% url 'player_event_management' %}" class="btn mybtn mybtn-small">{% trans "Event management" %}</a>
                <a href="{% url 'photo_gallery' %}" class="btn mybtn mybtn-small">{% trans "Photo gallery" %}</a>
                <a href="{% url 'team_management' %}" class="btn mybtn mybtn-small">{% trans "My teams" %}</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row block-bottom-line">
            <div class="col-md-6 text-center">
                <h3 class="color-header">{% blocktrans %}My score:{% endblocktrans %}</h3>
                {{ object.players.points }}
            </div>
            <div class="col-md-6 text-center">
                <h3 class="color-header">{% trans 'Rating' %}</h3>
                {{ object.players.rating }}
            </div>
        </div>
        {% if object.players.get_current_event %}
            <div class="row block-bottom-line">
                <div class="col-md-12">
                    <h2 class="color-header">{% blocktrans %}Today events{% endblocktrans %}</h2>
                    <table class="table table-responsive">
                        <thead>
                            <tr>
                                <th class="text-center">{% trans 'Title' %}</th>
                                <th class="text-center">{% trans 'Start date' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for event in object.players.get_current_event %}
                                <tr>
                                    <td class="text-center">
                                        <a href="{% url 'play_event' event.pk %}">
                                            <h4> {{ event.title }}</h4>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        {{ event.start_date|date:'d-m-Y H:i' }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-12">
                <h2 class="color-header">{% blocktrans %}Change personal info:{% endblocktrans %}</h2>
                <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {% trans 'Current avatar' %}:
                        {% if object.questsusers.image.url != None %}
                            <img src="{{ object.questsusers.image.url }}" class="img-responsive img-rounded content-icon block-icon avatar-image" alt="{{ object.username }}">
                        {% else %}
                            <img src="{% static 'images/no-players-image.png' %}" class="img-responsive img-rounded content-icon block-icon avatar-image" alt="{{ object.username }}">
                        {% endif %}
                        <br>
                        <label for="id_avatar">{% blocktrans %}Change avatar:{% endblocktrans %}</label>
                        <input id="id_avatar" name="avatar" type="file">
                    </div>
                    <div class="form-group">
                        <label for="id_email">{{ form.email.label }}:</label>
                        {{ form.email|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_description">{{ form.description.label }}:</label>
                        {{ form.description|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_date_of_birth">{{ form.date_of_birth.label }}:</label>
                        {{ form.date_of_birth|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_sex">{{ form.sex.label }}:</label>
                        {{ form.sex|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_country">{{ form.country.label }}:</label>
                        {{ form.country|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_city">{{ form.city.label }}:</label>
                        {{ form.city|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_street">{{ form.street.label }}:</label>
                        {{ form.street|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_phone">{{ form.phone.label }}:</label>
                        {{ form.phone|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_skype">{{ form.skype.label }}:</label>
                        {{ form.skype|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="id_site">{{ form.site.label }}:</label>
                        {{ form.site|add_class_to_formfield:"form-control" }}
                    </div>
                    <div class="checkbox">
                        <label>
                            {{ form.show_personal_info|add_class_to_formfield:"form-control" }}&nbsp;{{ form.show_personal_info.label }}
                        </label>
                    </div>
                    <input type="submit" value="{% trans 'Save!' %}" class="mybtn mybtn-small">
                </form>
            </div>
        </div>
    </div>
{% endblock %}